# Generated by Django 5.1.3 on 2024-11-28 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=63)),
            ],
            options={
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(fields=("name",), name="unique_tag_name")
                ],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                ("finish_time", models.DateTimeField(blank=True, null=True)),
                ("done", models.BooleanField(default=False)),
                ("tags", models.ManyToManyField(related_name="tasks", to="tasks.tag")),
            ],
            options={
                "ordering": ["done", "-created_time"],
            },
        ),
    ]
